---
 - hosts: host1
   connection: local
   tasks:
   - name: Downloading Sample War File
     get_url:
       url: http://10.127.126.113:8040/artifactory/charugarg_3802/com/nagarro/devops-tools/devops/demosampleapplication/1.0.0-SNAPSHOT/demosampleapplication-1.0.0-SNAPSHOT.war
       dest: /usr/share/tomcat/webapps/demosampleapplication.war
   - name: Stopping Tomcat
     command: sh /usr/share/tomcat/bin/shutdown.sh
   - name: Starting Tomcat
     command: sh /usr/share/tomcat/bin/startup.sh



